import {LpUtils} from "../utils";
import {
    IGenericActionUnit,
    ActionUnitParams,
    ActionUnitType, DEFAULT_UNNAMED_AU,
    ModTagValueTimed
} from "./action-unit.interface";

interface IHeartbeatAUParams extends ActionUnitParams {
    /**
     * This tags will be toggled: set to fromValue and then to toValue.
     * It used to reset Alarm generated by the Unit Test.
     */
    tagsToToggle: ModTagValueTimed[],
    /**
     * How long these heartbeats will last. 0 is runs till the end of the test.
     */
    duration_s: number,
}

export interface IHeartbeatAU extends IGenericActionUnit {
    readonly type: ActionUnitType.Heartbeat;
    params: IHeartbeatAUParams
}

export class HeartbeatAU implements IHeartbeatAU {
    desc: string = "";
    enabled: boolean = true;
    readonly id: string = LpUtils.generateId();
    // do not modify, it is a test property for new class
    modifiedOn: number = 0;
    readonly type: ActionUnitType.Heartbeat = ActionUnitType.Heartbeat;
    name: string;
    params: IHeartbeatAUParams;
    parentId: string;

    constructor(name: string, parentId: string) {
        this.name = name || DEFAULT_UNNAMED_AU;
        this.parentId = parentId;
        this.params = {
            sleepBefore: 0,
            sleepAfter: 0,
            tagsToToggle: [new ModTagValueTimed()],
            duration_s: 0,
        }
    }
}
